package com.ccink.resources

const val ItemDescriptionBackground = "Item description background"
const val ItemInformation = "Информация"
const val CharacterImage = "Character image"
const val CharactersCollection = "Коллекция персонажей"
const val SuitableClothes = "Подходящие комплекты"
const val CompatibleCharacters = "Совместимые персонажи"
const val Details = "Смотреть"
const val MeanIt = "Понятно"
const val AlreadyBought = "Куплено"
const val Happiness = "Ура!"
const val WearItOn = "Надеть"
const val HasWornOn = "Надето"
const val GoBack = "Назад"
const val CharacterPurchaseConfirmation = "Вы купили персонажа"
const val ClothesPurchaseConfirmation = "Вы купили комплект"
const val SomethingGoingWrong = "Что-то пошло не так..."
const val IOError = "Ошибка ввода-вывода"
const val NoData = "Нет данных"